config/routes.rb
Rails.application.routes.draw do
  
  root  'application#welcome'

  get '/users/:user_id/lists/favorites' => 'lists#favorites'

  resources :users do 
    resources :lists
  end
  resources :sessions, only: [:create, :destroy]

  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]

  match "*any", via: :all, to: "errors#not_found"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items

  validates :name, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category
  belongs_to :list, optional: true

end

app/models/list.rb
class List < ApplicationRecord

  belongs_to :user
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :lists

  has_secure_password

  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper 

  layout 'welcome'

  def welcome
    redirect_to user_lists_path(current_user) if logged_in?
    @user = User.new
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  
  layout nil
  
  def not_found
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :require_login

  layout 'application'

  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
    @items = Item.all
  end

  def create
    list = List.new(list_params)
    list.user = current_user
    list.save
    redirect_to user_lists_path(current_user)
  end

  def show
    @list = List.find_by(id: params[:id])
  end

  def edit
    @list = List.find_by(id: params[:id])
  end

  def update
    list = List.find_by(id: params[:id])
    list.update(list_params)
    redirect_to user_list_path(current_user, list)
  end

  def destroy
    List.find_by(id: params[:id]).destroy
    redirect_to user_lists_path(current_user)
  end

  def favorites
    @lists = current_user.lists.where(is_favorite: true)
    render :index
  end
  

  private

  def list_params
    params.require(:list).permit(:name, :is_favorite, item_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    if user.nil?
      @error = "No user with this email found"
      @user = User.new(email: params[:email])
      render "application/welcome"
    else
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_lists_path(user)
      else
        @error = "Invalid password"
        @user = User.new(email: params[:email])
        render "application/welcome"
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def google
    user = User.find_or_create_by(email: auth['email'])
    user.password = SecureRandom.hex(10) if user.password_digest.nil?
    user.save
    if user && user.id
      session[:user_id] = user.id
      redirect_to user_lists_path(user)
    else
      redirect_to root_path
    end
  end

  private 

  def auth
    request.env['omniauth.auth']['info']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(user_params)
    if user.valid?
      user.save
      session[:user_id] = user.id
      redirect_to user_lists_path(user)
    else
      @error = user.errors.full_messages.first
      @user = user
      render "application/welcome"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    session[:user_id] != nil
  end

  def require_login
    render 'errors/not_logged_in', :layout => nil if session[:user_id].nil?
  end

end

app/views/application/welcome.html.erb
<div class="welcome-page">

  <h1 style="text-align: center; padding-top: 5%;">Welcome</h1>

  <%if @error%>
    <div class="alert alert-danger text-center"><%=@error%></div>
  <%end%>

  <div style="justify-content: center; text-align: center; display:flex">
    <div style="width: 50%; text-align: center; max-width: 700px; min-width: 400px;">
      <%=form_tag sessions_path, class:'form-group' do%>
        <%= text_field_tag :email, nil, class:'form-control', placeholder:'Email Address', :required => true %>
        <br>
        <%= password_field_tag :password , nil, class:'form-control', placeholder:'Password', :required => true %>
        <br>
        <%=submit_tag 'Log In', class: "btn btn-primary"%>
      <%end%>
      <br>
      
        <p>Log In With <%=link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCuQzA6GQf1JbgkvFCUvDxAN0S5yOiYvdog&usqp=CAU",width: 50, height: 50 ), '/auth/google_oauth2', method:'post' %></p>
        
      <br>
      <h3>Or Sign Up</h3>
        <%=form_for @user, class:'form-group' do |f| %>
          <%=f.text_field :email, class:"form-control", placeholder:'Email', :required => true %>
          <br>
          <%=f.password_field :password, class:"form-control", placeholder:'Password' %>
          <br>
          <%=f.password_field :password_confirmation, class:"form-control", placeholder:'Confirm Password'%>
          <br>
          <div class="text-center"><br><%=f.submit  class: "btn btn-primary "%></div>
        <%end%>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodcalcAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%=user_lists_path(current_user)%>>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/<%=session[:user_id]%>/lists/favorites">Favorites</a>
        </li>
        <li class="nav-item">
          <%=form_tag "/sessions/#{session[:user_id]}", method:'delete', class:"nav-item nav-link" do%>
            <%=submit_tag 'Log Out', class:"nav-link btn btn-danger"%>
          <%end%>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodcalcAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/lists/edit.html.erb
<div class="display-4 text-center" >Edit '<%=@list.name%>' list</div>
<br>
<div style="justify-content: center; text-align: center; display: flex;">
  <div style="width: 60%; min-width:500px;">
    <%=form_for [current_user, @list], class:'form-group' do |f|%>
      <%=f.text_field :name, class:"form-control", placeholder:'name', :required => true %>
      <br>
      <%= f.label "Make List favorite" %> 
      <br>
      <%=f.check_box :is_favorite%>
      <br>
      <h3>Add Items to the list</h3>

      <%=collection_check_boxes(:list, :item_ids, Item.all, :id, :name) do |item|%>
        <br>
        <%=item.label(:"data-value" => item.value) { item.check_box + item.text }%>
      <%end%>

      <br> <br/>
      <div style='justify-content:center; text-align:center;'>
        <%=f.submit 'Update List', class: "btn btn-primary "%>
      </div>
    <%end%>
      <br> <br/>
      <div style="padding-bottom: ">
        <%=form_tag user_list_path(current_user, @list), method:"delete" do %>
          <%=submit_tag "Delete List", class:"btn btn-danger"%>
        <%end%>
      </div>
  </div>
</div>

app/views/lists/index.html.erb
<br>
<div class="text-center">
  <%if @lists.size > 0%>
    <h3>Your Lists:</h3>
    <br>
    <%@lists.each do |list|%>
    <a href=<%=user_list_path(current_user, list)%>><p><%=list.name%></p></a>
    <%end%>
  <%else%>
    <h3 >You don't have lists yet</h3>
  <%end%>
</div>

<a href=<%=new_user_list_path(current_user)%> class='text-center'><p style="color: green; padding-top: 8%;">create new list</p></a>

app/views/lists/new.html.erb
<div class="display-4 text-center">Create a new list</div>
<br>
<div style="justify-content: center; text-align: center; display: flex;">
  <div style="width: 60%; min-width:500px;">
    <%=form_for [current_user, @list], class:'form-group' do |f|%>
      <%=f.text_field :name, class:"form-control", placeholder:'name', :required => true %>
      <br>
      <%= f.label "Make List favorite" %> 
      <br>
      <%=f.check_box :is_favorite%>
      <br>
      <h3>Add Items to the list</h3>

      <%=collection_check_boxes(:list, :item_ids, Item.all, :id, :name) do |item|%>
        <br>
        <%=item.label(:"data-value" => item.value) { item.check_box + item.text }%>
      <%end%>

      <br> <br/>
      <div style='justify-content:center; text-align:center;'>
        <%=f.submit 'Create New List', class: "btn btn-primary "%>
      </div>
    <%end%>
  </div>
</div>

app/views/lists/show.html.erb
<h2 class=text-center>
  <%=@list.name%>
  <%if @list.is_favorite%>
  <span>
    <img src='https://cdn.iconscout.com/icon/free/png-512/star-bookmark-favorite-shape-rank-like-32386.png' style="width: 50px; height: 50px;">
  </span>
  <%end%>
</h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <%counter = 1 %>
    <%@list.items.each do |item|%>
      <tr>
        <th scope="row"><%=counter%></th>
        <td><%=item.name%></td>
        <td><%=item.description%></td>
      </tr>
      <%counter += 1%>
    <%end%>
  </tbody>
</table>

<br>

<div style="justify-content: center; text-align: center; display: flex">
  <a href=<%=edit_user_list_path(current_user, @list)%>><p class="btn btn-primary">Edit</p></a>
</div>